---
  swagger: "2.0"
  info: 
    title: "Lightweight Contact Events Service"
    description: "Stores a history of events"
    version: "0.1.0"
  basePath: "/lightweight-contact-events"
  consumes:
    - application/json
  produces: 
    - application/json
